IBM/nodejs-idb-pconnector

- README.md
Links were pointing to the bitbucket repo
fixes  #1
> Fixes broken links

- CONTRIBUTING.md
> Add Contributing Guidelines as per issue #3

- .github/dco.yml
- CHANGELOG.md
- README.md
- examples/pool.js
- package.json
Slight updates to get ready to release 1.0.3
Update README
- Add TOC
- Update examples
- Update Contributing
Add DCO bot config to skip org members
Bump version in package.json
Add CHANGELOG.md
> Updates and Prep to release 1.0.3

- lib/idb-pconnector.js
See issue #32 for full details
> Patched require issue outlined in issue #32

- lib/dbPool.js
> Don't throw error if parameter value for prepareExecute() is null

- lib/connection.js
- lib/statement.js
> Add createConnection method

- test/statementTest.js
> [statementTest.js] Add test case for binding a null value

- README.md
- docs/README.md
- lib/connection.js
- test/connectionTest.js
As this is this the most requested topic I get from clients, I thought it might be worth adding this API.
I have created and the API, tested it, added to the readme and added the documentation.
Let me know if there is anything else I should do.
Thanks!
Signed-off-by: Liam Allan <WorksOfLiam@users.noreply.github.com>
> Implementation of setLibraryList API

- package.json
- updated eslint, eslint-plugin-import, had vulnerabilities high
lodash
- updated other deps
Here is the log from `npm audit` :
```
found 7 vulnerabilities (1 moderate, 5 high, 1 critical)
run `npm audit fix` to fix them, or `npm audit` for details
Moderate        Denial of Service                                             
Package         js-yaml                                                       
Dependency of   eslint [dev]                                                  
Path            eslint > js-yaml                                              
More info       https://npmjs.com/advisories/788                              
High            Code Injection                                                
Package         js-yaml …
```
> [package.json] Update deps

- lib/dbPool.js
> [dbPool.js] Patch prepareExecute #48

- package.json
Bump version for new npm release.
> Bump version to 1.0.8

- .github/workflows/sematic-pull-requests.yml
> ci: Add PR title linter following conventional commits 

- .github/workflows/stale.yml
> ci: Add workflow to mark stale issues and PRs 

- docs/README.md
- lib/statement.js
- test/statementTest.js
> Add enableNumericTypeConversion()

- docs/README.md
- lib/statement.js
- package.json
- test/statementTest.js
We want master as our dev branch.
> refactor: Add changes from v1.1.0-dev

- package.json
> build: Update version to 1.1.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> ci: Add issue templates 

- lib/dbPool.js
- test/dbpoolTest.js
> revert: "feat: DBPool now emits 'new connection' event (#76)"

- .gitignore
- package-lock.json
> fix: Add package-lock.json

- .github/workflows/stale.yml
> ci: Add exempt-pr-label to stale action

- README.md
- docs/README.md
- lib/statement.js
- package.json
- test/statementTest.js
> feat: Add support for bindParameters

- package-lock.json
- package.json
> build: Add standard-version

- .github/workflows/eslint.yml
- package.json
> ci: Add eslint action

- package.json
> build: Update deps to latest version
